import LeanTea
import LeanTea.Site

/-! # static_site — build, serve or scaffold a static site

```
$ static_site new mysite                       # scaffold a starter site
$ static_site build mysite [--out _site] [--title "My site"] [--base-url https://…] [--drafts]
$ static_site serve mysite [--out _site] [--port 8080]   # rebuilds on change
```

See `LeanTea.Site` for the source layout and template bindings. -/

open LeanTea

namespace StaticSite

structure Args where
  cmd     : String := ""
  src     : String := ""
  out?    : Option String := none
  title   : String := "Site"
  tagline : String := ""
  baseUrl : String := ""
  port    : UInt16 := 8080
  drafts  : Bool := false

partial def parseArgs : List String → Args → Args
  | "--out" :: v :: r, a      => parseArgs r { a with out? := some v }
  | "--title" :: v :: r, a    => parseArgs r { a with title := v }
  | "--tagline" :: v :: r, a  => parseArgs r { a with tagline := v }
  | "--base-url" :: v :: r, a => parseArgs r { a with baseUrl := v }
  | "--port" :: v :: r, a     => parseArgs r { a with port := (v.toNat?.getD 8080).toUInt16 }
  | "--drafts" :: r, a        => parseArgs r { a with drafts := true }
  | x :: r, a =>
    if a.cmd.isEmpty then parseArgs r { a with cmd := x }
    else if a.src.isEmpty then parseArgs r { a with src := x }
    else parseArgs r a
  | [], a => a

/-! ## Scaffold -/

def starter : List (String × String) := [
  ("_layouts/default.html", "<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>{{title}} · {{site_title}}</title>
  <link rel=\"stylesheet\" href=\"{{root}}style.css\">
</head>
<body>
  <header>
    <a class=\"brand\" href=\"{{root}}index.html\">{{site_title}}</a>
    <nav>{{#each nav}}<a class=\"{{current}}\" href=\"{{root}}{{url}}\">{{title}}</a>{{/each}}</nav>
  </header>
  <main>
{{content}}
  </main>
  {{#include \"_includes/footer.html\"}}
</body>
</html>
"),
  ("_includes/footer.html", "<footer>Generated by <code>static_site</code> (LeanTea.Site)</footer>\n"),
  ("style.css", ":root{--bg:#fbfbfa;--fg:#1d2330;--muted:#6b7280;--acc:#2563eb;--line:#e5e7eb}
@media (prefers-color-scheme:dark){:root{--bg:#14161b;--fg:#e6e8ee;--muted:#9aa1ad;--acc:#7aa2ff;--line:#2b3038}}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.65 -apple-system,'Hiragino Sans',sans-serif}
header,main,footer{max-width:760px;margin:0 auto;padding:16px}
header{display:flex;gap:20px;align-items:baseline;flex-wrap:wrap;border-bottom:1px solid var(--line)}
.brand{font-weight:700;color:var(--fg);text-decoration:none}
nav a{margin-right:14px;color:var(--muted);text-decoration:none}nav a.current{color:var(--acc)}
a{color:var(--acc)}pre{overflow-x:auto;background:rgba(127,127,127,.1);padding:12px;border-radius:6px}
footer{color:var(--muted);font-size:14px;border-top:1px solid var(--line)}
.posts{list-style:none;padding:0}.posts time{color:var(--muted);margin-right:10px;font-variant-numeric:tabular-nums}
"),
  ("index.html", "---
title: Home
order: 0
nav: true
---
<h1>Welcome</h1>
<p>This site is generated by <code>LeanTea.Site</code>. Edit the files under the source directory and run
<code>static_site serve</code>.</p>
<h2>Posts</h2>
<ul class=\"posts\">
{{#each posts}}  <li><time>{{date}}</time><a href=\"{{root}}{{url}}\">{{title}}</a></li>
{{/each}}</ul>
"),
  ("about.md", "---
order: 1
---
# About

A Markdown page. Links to other pages use their source name, e.g.
[the first post](posts/hello.md), and are rewritten to `.html`.
"),
  ("posts/hello.md", "---
title: Hello, world
date: 2026-10-01
nav: false
---
# Hello, world

The first post. Files under `posts/` are listed on the home page,
newest `date` first.

```lean
#eval \"hello\"
```
"),
  ("posts/second.md", "---
title: A second post
date: 2026-10-05
nav: false
---
# A second post

Back to [about](../about.md).
")]

def scaffold (dir : System.FilePath) : IO Unit := do
  if ← dir.pathExists then
    if !(← dir.readDir).isEmpty then
      throw <| IO.userError s!"{dir} exists and is not empty"
  for (rel, body) in starter do
    let p := dir / rel
    if let some d := p.parent then IO.FS.createDirAll d
    IO.FS.writeFile p body
  IO.println s!"created {dir}/ — next: static_site serve {dir}"

def main (argv : List String) : IO UInt32 := do
  let a := parseArgs argv {}
  if a.src.isEmpty || !["new", "build", "serve"].contains a.cmd then
    IO.eprintln "usage: static_site new|build|serve <dir> [--out DIR] [--title T] [--base-url URL] [--port N] [--drafts]"
    return 2
  if a.cmd == "new" then
    scaffold a.src
    return 0
  let cfg : Site.Config := {
    srcDir := a.src, outDir := a.out?.getD "_site", siteTitle := a.title,
    tagline := a.tagline, baseUrl := a.baseUrl, includeDrafts := a.drafts }
  if a.cmd == "serve" then
    Site.serve cfg a.port
    return 0
  let r ← Site.build cfg
  IO.println s!"static_site: {r.pages.length} pages + {r.assets} assets → {cfg.outDir}/"
  return 0

end StaticSite

def main (argv : List String) : IO UInt32 := StaticSite.main argv
